name: "Podcast Generator"
author: "Ohioze Alex Omiunu"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
   icon: "git-branch"
   color: "blue"
inputs:
    email:
      description: The commiter's email address
      required: true
      default: #{{github.actor}}@localhost
    name:
      description: The committer's name
      required: true
      default: ${{github.actor}}
